[package]
name = "tic-tac-toe-brackets"
version = "0.1.0"
authors = ["Matthew Scott Conroy <matthewscottconroy@gmail.com>"]
edition = "2021"

[dependencies]
bracket-lib = "~0.8.1"
tic-tac-toe-lib = { path = "../tic-tac-toe-lib" }

