[package]
name = "virtual-joystick"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/matthewscottconroy/tiny-rust-games"
description = "virtual-joystick: An on-screen joystick Control drawn entirely in Rust"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
godot = "0.5"
