[package]
name = "grid-movement"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/matthewscottconroy/tiny-rust-games"
description = "grid-movement: Demonstrates tile-based movement with a queue of pending"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
godot = "0.5"
