#!/usr/bin/env python3
"""Generate the cross-engine parity matrix from the demos themselves.

The catalogue answers "what demos are there?". This answers a question a
contributor is more likely to have: "what exists for one engine but not the
other?" — which is both the honest state of goal #2 and the most useful
"what should I build next" list the repository can offer.

Like the catalogue it is generated from the demo directories, so it cannot
drift from the source the way a hand-written table does.

    python3 tools/parity.py            # write docs/PARITY.md
    python3 tools/parity.py --check    # fail if it is out of date
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

# Reuse the catalogue's collector rather than re-deriving the demo list; two
# scanners that could disagree about what a demo is would be exactly the kind
# of drift both tools exist to prevent.
from catalogue import ROOT, collect  # noqa: E402

OUTPUT = ROOT / "docs" / "PARITY.md"

# Engines compared, in column order.
ENGINES = [("bevy", "Bevy"), ("godot", "Godot"), ("brackets", "bracket-lib")]

HEADER = """<!-- Generated by tools/parity.py — do not edit by hand. -->
# Cross-engine parity

Which concepts are demonstrated in which engine. Generated from the demo
directories, so it cannot drift; regenerate with `just parity`.

Goal #2 asks for the same ideas across as many libraries as possible. This is
where that stands — and a gap here is not a defect, it is a suggestion. A demo
that exists for one engine and not another is the cheapest possible contribution
to make, because the hard part (deciding what to teach) is already done.

Concepts are matched by directory name, which **undercounts**: `object-pool`
and `object-pooling` are the same idea filed under two names. The last section
lists those near-misses rather than guessing, because the fix is a judgement
call — either they are the same demo and one should be renamed, or they are
genuinely different and the similar names are the problem.

"""


def build() -> str:
    demos = collect()

    by_engine: dict[str, set[str]] = {key: set() for key, _ in ENGINES}
    for demo in demos:
        by_engine.setdefault(demo["engine"], set()).add(demo["name"])

    every_name = sorted({demo["name"] for demo in demos})

    lines = [HEADER]

    # Summary first: the counts are the headline.
    lines.append("| Engine | Demos |")
    lines.append("|--------|-------|")
    for key, label in ENGINES:
        lines.append(f"| {label} | {len(by_engine.get(key, ()))} |")
    shared = by_engine.get("bevy", set()) & by_engine.get("godot", set())
    lines.append(f"| **In both Bevy and Godot** | **{len(shared)}** |")
    lines.append("")

    bevy_only = sorted(by_engine.get("bevy", set()) - by_engine.get("godot", set()))
    godot_only = sorted(by_engine.get("godot", set()) - by_engine.get("bevy", set()))

    lines.append(
        f"{len(shared)} concepts are demonstrated in both engines. "
        f"{len(bevy_only)} exist only in Bevy and {len(godot_only)} only in "
        "Godot; those two lists are the backlog."
    )
    lines.append("")

    lines.append("## Every concept")
    lines.append("")
    head = "| Concept | " + " | ".join(label for _, label in ENGINES) + " |"
    lines.append(head)
    lines.append("|---------|" + "|".join([":---:"] * len(ENGINES)) + "|")
    for name in every_name:
        cells = []
        for key, _ in ENGINES:
            present = name in by_engine.get(key, set())
            cells.append("✓" if present else "·")
        lines.append(f"| `{name}` | " + " | ".join(cells) + " |")
    lines.append("")

    near = []
    for name in godot_only:
        match = difflib.get_close_matches(name, bevy_only, n=1, cutoff=0.75)
        if match:
            near.append((name, match[0]))

    for title, names, other in (
        ("Only in Bevy", bevy_only, "Godot"),
        ("Only in Godot", godot_only, "Bevy"),
    ):
        lines.append(f"## {title}")
        lines.append("")
        if names:
            lines.append(f"Candidates for a {other} port:")
            lines.append("")
            for name in names:
                lines.append(f"- `{name}`")
        else:
            lines.append(f"Nothing — every concept here also exists in {other}.")
        lines.append("")

    lines.append("## Probably the same concept, filed under two names")
    lines.append("")
    if near:
        lines.append(
            "Counted as gaps above, because the matrix matches on directory "
            "name. Each pair is either one demo needing a consistent name, or "
            "two demos whose names should be less alike:"
        )
        lines.append("")
        lines.append("| Godot | Bevy |")
        lines.append("|-------|------|")
        for godot_name, bevy_name in near:
            lines.append(f"| `{godot_name}` | `{bevy_name}` |")
    else:
        lines.append("None — no two demo names are close enough to be confused.")
    lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed matrix is stale",
    )
    args = parser.parse_args()

    page = build()
    if args.check:
        if not OUTPUT.exists():
            print(f"{OUTPUT} does not exist; run: python3 tools/parity.py")
            return 1
        if OUTPUT.read_text(encoding="utf-8") != page:
            print(f"{OUTPUT} is out of date; run: python3 tools/parity.py")
            return 1
        print(f"{OUTPUT} is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(page, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
